#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:


Display stick table:

cd $(dirname $(readlink -f $0))
for i in \$(seq 5); do \\
  curl -w '\n' -D - -X POST -H "Content-Type: application/json" \\
    --data-binary "{\"username\":\"admin\",\"password\":\"admin\$i\"}"  \\
    $proxy_root/api/login; \\
   sudo socat - ./haproxy.sock  <<<"show table mypeers/per_src_brute_force"; \\
   echo; \\
done


Brute force:

for i in \$(seq 5); do \\
  curl -w '\n' -D - -X POST -H "Content-Type: application/json" \\
     --data-binary "{\"username\":\"admin\",\"password\":\"admin\$i\"}" \\
     $proxy_root/api/login; \\
   echo; \\
done


EOF

haproxy_start
