#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:

for p in \\
  /user/user/admin \\
  /api/invalid \\
  /user/profile \\
  /api/user \\
  /api/logout \\
  /api/profile \\
  /logout; do \\
    echo "-> \$p"; \\
    curl -w '\n' -D - -s -o /dev/null \\
       -H "authorization: Bearer $jwt" \\
      "$proxy_root\$p"; \\
done

EOF

haproxy_start
