#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:

for m in GET POST PUT OPTIONS HEAD DELETE PATCH; do \\
  echo \$m; \\
  curl -H "authorization: Bearer $jwt" -X \$m "$proxy_root/logout"; \\
  echo; \\
done





0xa5:



Register john:
curl -X POST -H 'content-type: application/json' \\
  --data-binary '{"username":"john","password":"doe"}' \\
  $root/api/register

No protection:
curl -H "authorization: Bearer $jwt" \\
  -X DELETE "$root/api/user/john"



Register john:
curl -X POST -H 'content-type: application/json' \\
  --data-binary '{"username":"john","password":"doe"}' \\
  $root/api/register

With protection:
curl -v -H "authorization: Bearer $jwt" \\
  -X DELETE "$proxy_root/api/user/john"


EOF

haproxy_start
