#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:

Regular JWT
curl -w '\n' -D - -H "authorization: Bearer $jwt" $proxy_root/api/user/$user


0xa7:

Invalid JWT


No protection:
curl -w '\n' -s -D /dev/stderr -H 'authorization: Bearer Invalid=-JWT' $root/api/user/$user | jq

With protection:
curl -w '\n' -D - -H 'authorization: Bearer Invalid=-JWT' $proxy_root/api/user/$user



EOF

haproxy_start
