#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:

0xa8:

Clean up:
docker  exec -it  mongodb mongosh dvapi --eval  'db.tickets.deleteMany({});'

No protection:
for i in \$(seq 161); do \\
  echo -n "\$i "; \\
   curl -w '\n' -s -H 'authorization: Bearer $jwt' \\
     -X POST -H 'content-type: application/json' \\
     --data-binary '{"message": "test"}' \\
     $root/api/addTicket; \\
done


Clean up:
docker  exec -it  mongodb mongosh dvapi --eval  'db.tickets.deleteMany({});'

With protection:
for i in \$(seq 10); do \\
  echo -n "\$i "; \\
  curl -w '\n' -s -H 'authorization: Bearer $jwt' \\
    -X POST -H 'content-type: application/json' \\
    --data-binary '{"message": "test"}' \\
    $proxy_root/api/addTicket; \\
done


EOF

haproxy_start
