#!/bin/bash

. ../common

cat<<xEOF

browser: 
  $proxy_root


curl:

0xa8:

docker  exec -it  mongodb mongosh dvapi --eval  'db.tickets.deleteMany({});'
for i in \$(seq 161); do echo -n "\$i "; curl -s  -H 'authorization: Bearer $jwt' -X POST -H 'content-type: application/json' --data-binary '{"message": "test"}' $root/api/addTicket; echo; done

docker  exec -it  mongodb mongosh dvapi --eval  'db.tickets.deleteMany({});'
for i in \$(seq 161); do echo -n "\$i "; curl -s  -H 'authorization: Bearer $jwt' -X POST -H 'content-type: application/json' --data-binary '{"message": "test"}' $proxy_root/api/addTicket; echo; done


xEOF

haproxy_start
