#!/bin/bash

. ../common

img_root=$(readlink -f ./..)

cat<<EOF

browser: 
  $proxy_root


curl:

0xa4:

No protection:
curl -w '\n' -D - -H "authorization: Bearer $jwt" -X POST -F "file=@$img_root/large-picture.jpg" $root/api/profile/upload


With protection:
curl -w '\n' -D - -H "authorization: Bearer $jwt" -X POST -F "file=@$img_root/large-picture.jpg" $proxy_root/api/profile/upload

EOF

haproxy_start
