#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:

0xa3:


Delete User John if exists:
curl -o /dev/null -s -X DELETE -H "authorization: Bearer $jwt" $root/api/user/john


no protection:
curl -w '\n' -D - -X POST -H 'content-type: application/json' \\
  --data-binary '{"username":"john","password":"doe","score":123456}' \\
  $root/api/register

Validate Flag (optional):
curl -X POST -v -H 'content-type: application/json' \\
  --data-binary '{"username":"john","password":"doe"}' \\
  $root/api/login 2>&1 \\
    | grep Authorization \\
    | sed 's/\r//g' \\
    | awk '{print \$4}' \\
    |  xargs -I{} \\
  curl -X GET -s -H "authorization: Bearer {}" $root/api/scores \\
  | jq


Delete User John:
curl -o /dev/null -s -X DELETE -H "authorization: Bearer $jwt" $root/api/user/john

With protection:
curl -w '\n' -D - -X POST  -H 'content-type: application/json' \\
   --data-binary '{"username":"john","password":"doe","score":123456}' \\
   $proxy_root/api/register



0xa9:

No protection:
curl -s -H "authorization: Bearer $jwt" \\
  -X POST -H 'content-type: application/json' \\
  --data-binary '{"unreleased": 1}' \\
  $root/api/allChallenges | jq

With protection:
curl -w '\n' -D - -s -H "authorization: Bearer $jwt" \\
  -X POST -H 'content-type: application/json' \\
  --data-binary '{"unreleased": 1}' \\
  $proxy_root/api/allChallenges


EOF

haproxy_start
