#!/bin/bash

. ../common

cat<<EOF

browser: 
  $proxy_root


curl:

0x10:

No protection:
curl -w '\n' -D - -X POST -H 'content-type: application/json' \\
  --data-binary '{"username":"admin","password":{"\$ne":null}}' \\
  $root/api/login

With protection:
curl -w '\n' -D - -X POST -H 'content-type: application/json' \\
  --data-binary '{"username":"admin","password":{"\$ne":null}}' \\
  $proxy_root/api/login



EOF

haproxy_start
